export const tempDataPT = [
  {
    id: "D0",
    default: true,
    name: "最大范围",
    ww: 20000,
    wl: 10000,
    hotkey: "0",
    key: "maxRange",
  },
  {
    id: "D1",
    default: true,
    name: "默认",
    ww: 10000,
    wl: 0,
    hotkey: "1",
    key: "defaultWWWL",
  },
  {
    id: "D2",
    default: true,
    name: "Suv 0-3",
    min: 0,
    max: 3,
    ww: 10000,
    wl: 0,
    hotkey: "2",
    key: "Range1",
  },
  {
    id: "D3",
    default: true,
    name: "Suv 0-5",
    min: 0,
    max: 5,
    ww: 12000,
    wl: 0,
    hotkey: "3",
    key: "Range2",
  },
  {
    id: "D4",
    default: true,
    name: "Suv 0-7",
    min: 0,
    max: 7,
    ww: 13000,
    wl: 0,
    hotkey: "4",
    key: "Range3",
  },
  {
    id: "D5",
    default: true,
    name: "Suv 0-10",
    min: 0,
    max: 10,
    ww: 14000,
    wl: 0,
    hotkey: "5",
    key: "Range4",
  },
  {
    id: "D6",
    default: true,
    name: "Suv 0-15",
    min: 0,
    max: 15,
    ww: 15000,
    wl: 0,
    hotkey: "6",
    key: "Range5",
  },
  {
    id: "D7",
    default: true,
    name: "Suv 0-20",
    min: 0,
    max: 20,
    ww: 16000,
    wl: 0,
    hotkey: "7",
  },
  {
    id: "D8",
    default: true,
    name: "Suv 0-25",
    min: 0,
    max: 25,
    ww: 17000,
    wl: 0,
    hotkey: "8",
  },
  {
    id: "D9",
    default: true,
    name: "Suv 0-30",
    min: 0,
    max: 30,
    ww: 18000,
    wl: 0,
    hotkey: "9",
  },
];

export const shortcutsKey = {
  D0: {
    effect: "调窗快捷键0",
    enable: true,
    key: 48,
    keyName: "0",
  },
  D1: {
    effect: "调窗快捷键1",
    enable: true,
    key: 49,
    keyName: "1",
  },
  D2: {
    effect: "调窗快捷键2",
    enable: true,
    key: 50,
    keyName: "2",
  },
  D3: {
    effect: "调窗快捷键3",
    enable: true,
    key: 51,
    keyName: "3",
  },
  D4: {
    effect: "调窗快捷键4",
    enable: true,
    key: 52,
    keyName: "4",
  },
  D5: {
    effect: "调窗快捷键5",
    enable: true,
    key: 53,
    keyName: "5",
  },
  D6: {
    effect: "调窗快捷键6",
    enable: true,
    key: 54,
    keyName: "6",
  },
  D7: {
    effect: "调窗快捷键7",
    enable: true,
    key: 55,
    keyName: "7",
  },
  D8: {
    effect: "调窗快捷键8",
    enable: true,
    key: 56,
    keyName: "8",
  },
  D9: {
    effect: "调窗快捷键9",
    enable: true,
    key: 57,
    keyName: "9",
  },
  imgSave: {
    effect: "截图下载",
    enable: true,
    key: 83,
    keyName: "s",
  },
  Page: {
    effect: "翻页",
    enable: true,
    key: 90,
    keyName: "z",
  },
  Window: {
    effect: "调窗",
    enable: true,
    key: 65,
    keyName: "a",
  },
  Ruler: {
    effect: "标注尺",
    enable: true,
    key: 69,
    keyName: "e",
  },
  Rect: {
    effect: "矩形",
    enable: true,
    key: 81,
    keyName: "q",
  },
  Pen: {
    effect: "智能画笔",
    enable: true,
    key: 84,
    keyName: "t",
  },
  Circle: {
    effect: "圆形",
    enable: true,
    key: 87,
    keyName: "w",
  },
  Angle: {
    effect: "角度",
    enable: true,
    key: 86,
    keyName: "v",
  },
  Pan: {
    effect: "平移",
    enable: true,
    key: 88,
    keyName: "x",
  },
  ACross: {
    effect: "十字定位线",
    enable: true,
    key: 67,
    keyName: "c",
  },
  delMark: {
    effect: "删除所有标注",
    enable: true,
    key: 82,
    keyName: "r",
  },
  Up: {
    effect: "向上翻页",
    enable: true,
    key: 38,
    keyName: "ArrowUp",
  },
  Down: {
    effect: "向下翻页",
    enable: true,
    key: 40,
    keyName: "ArrowDown",
  },
  Top: {
    effect: "置顶",
    enable: true,
    key: 36,
    keyName: "Home",
  },
  Bottom: {
    effect: "置底",
    enable: true,
    key: 35,
    keyName: "End",
  },
  Reset: {
    effect: "重置",
    enable: true,
    key: 70,
    keyName: "f",
  },
  Delete: {
    effect: "删除标注",
    enable: true,
    key: 46,
    keyName: "Delete",
  },
};

export const positionLine = {
  // 十字定位线
  default: {
    color1: "#25a5ad",
    color2: "#25a5ad",
    dottedLine1: [], // 空数组代表实线, [1, 1]: 虚线长度1，实线长度1，虚线长度1，实线...
    dottedLine2: [],
  },
  curViewMod0: {
    color1: "#3470d8",
    color2: "#cd9700",
    dottedLine1: [],
    dottedLine2: [],
  },
  curViewMod1: {
    color1: "#8a00da",
    color2: "#cd9700",
    dottedLine1: [],
    dottedLine2: [],
  },
  curViewMod2: {
    color1: "#8a00da",
    color2: "#3470d8",
    dottedLine1: [],
    dottedLine2: [],
  },
};
